healthCheckTimeout: 500

logLevel: info

macros:
  "latest-llama": >
    /home/procastoh/AI/llama-cpp/build/bin/llama-server
  "default_ctx": 96000
  "model_dir": "/home/procastoh/AI/LLM-Models/LLM/"
  "options": "-ctk q8_0 -ctv q8_0 -c 96000 --n-gpu-layers 30"

apiKeys:
  - "ph"
  - "ph-w8JhvNe7I+64W3HvEVS2C9LBdyc2fRlwwlXdXbBjnx2xfV/9kgn+zMbPUm87NtBN"

models:
  "Qwythos-9B-Q8_0":
    name: "Qwythos-9B"

    cmd: |
      ${latest-llama}
      --port ${PORT}
      --model ${model_dir}/Qwythos-9B-Q8_0.gguf
      ${options}

  "gemma-4-12b-quant":
    name: "gemma-4-12b"

    cmd: |
      ${latest-llama}
      --port ${PORT}
      --model ${model_dir}/gemma-4-12b-quant.gguf
      ${options}

  "gpt-oss-quant":
    name: "GPT-OSS"
    cmd: |
      ${latest-llama}
      --port ${PORT}
      --model ${model_dir}/gpt-oss-quant.gguf
      ${options}
